/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface LoadingOverlay {
    /**
    * The first name
    */
    'showing': boolean;
  }
}

declare global {


  interface HTMLLoadingOverlayElement extends Components.LoadingOverlay, HTMLStencilElement {}
  var HTMLLoadingOverlayElement: {
    prototype: HTMLLoadingOverlayElement;
    new (): HTMLLoadingOverlayElement;
  };
  interface HTMLElementTagNameMap {
    'loading-overlay': HTMLLoadingOverlayElement;
  }
}

declare namespace LocalJSX {
  interface LoadingOverlay {
    /**
    * The first name
    */
    'showing'?: boolean;
  }

  interface IntrinsicElements {
    'loading-overlay': LoadingOverlay;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'loading-overlay': LocalJSX.LoadingOverlay & JSXBase.HTMLAttributes<HTMLLoadingOverlayElement>;
    }
  }
}


